version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - '8000'
    environment:
      - REDIS_URL=${REDIS_URL}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
    depends_on:
      - elasticsearch
      - redis

  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    ports:
      - '9200'
    environment:
      - "discovery.type=single-node"

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379'

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    ports:
      - '8000'
    volumes:
      - ./:/app/
    environment:
      - REDIS_URL=${REDIS_URL}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - API_URL=${API_URL}
    entrypoint: >
      sh -c "python3 utils/wait_for_es.py
      && python3 utils/wait_for_redis.py
      && pytest api/v1 -vv"
    depends_on:
      - backend
