version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000'
    environment:
      - REDIS_URL=${REDIS_URL}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
    depends_on:
      - elasticsearch
      - redis

  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    ports:
      - '9200'
    environment:
      - "discovery.type=single-node"
    volumes:
      - ${HOST_PATH_ES}:/usr/share/elasticsearch/data

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379'
    volumes:
      - ${HOST_PATH_REDIS}:/var/lib/redis/data

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - api
